default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: flake8
        exclude: (tests|^docs/conf.py)

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.4
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
